<a href="https://colab.research.google.com/github/Colsai/DATA-690-WANG/blob/master/Assignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment #03
1. Explore College Scorecard website - https://collegescorecard.ed.gov/ 

2. Explore College Scorecard Data web page - https://collegescorecard.ed.gov/data/

3. Download and skim the documentation - https://collegescorecard.ed.gov/assets/FullDataDocumentation.pdf

4. Download the dataset - https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data.zip (265MB Zip File)

5. Unzip the file into a folder (there are many files, one for each school year)

6. Import the 2017-2018 school year file "MERGED2017_18_PP.csv" and explore:   

    * how many colleges or rows?   

    * how many variables or columns?   

    * Look at the first 20 rows   

    * look at the last 20 rows   

    * Look at a random sample of 20 rows    

7. Since there are too many variables to explore, many of which are not interesting. Modify your import statement to only import the following 9 variables:

- UNITID
- INSTNM
- CITY
- STABBR
- ZIP
- ADM_RATE
- UGDS
- TUITIONFEE_IN
- MN_EARN_WNE_P10 

8. Download and read the data dictionary file - https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx

Find out the definition of the above 9 variables and document the definitions in the Jupyter Notebook so that the readers will not need to repeat what you have done to know the meaning of these variables.

9. Use the predefined cells below to conduct and document your data exploration.

When in doubt, Google. Find examples and read documents/tutorials. 

Have fun!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
# Import libraries
import pandas as pd
import numpy as np

In [ ]:
# load the 2017-2018 school year file "MERGED2017_18_PP.csv"   
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/CollegeScorecard_Raw_Data/MERGED2018_19_PP.csv")

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (9,1725,1726,1727,1728,1729,1743,1815,1816,1817,1818,1823,1824,1830,1831,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1909,1910,1911,1912,1913,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1983,1984) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
# Find out how many colleges or rows?   
print(df.size)
# Find out how many variables or columns? 
print(df.shape)
df.dtypes

13516716
(6806, 1986)

UNITID                        int64
OPEID                         int64
OPEID6                        int64
INSTNM                       object
CITY                         object
                             ...
SCUGFFN                     float64
POOLYRS_FTFTAIDPCT          float64
FTFTPCTPELL_POOLED_SUPP      object
FTFTPCTFLOAN_POOLED_SUPP     object
SCUGFFN_POOLED              float64
Length: 1986, dtype: object

In [ ]:
# Look at the first 20 rows  
df.head(20)

    UNITID    OPEID  ...  FTFTPCTFLOAN_POOLED_SUPP SCUGFFN_POOLED
0   100654   100200  ...                    0.7287         2698.0
1   100663   105200  ...                    0.5414         4176.0
2   100690  2503400  ...         PrivacySuppressed           24.0
3   100706   105500  ...                    0.4402         2544.0
4   100724   100500  ...                    0.7464         2094.0
5   100751   105100  ...                    0.4094        14863.0
6   100760   100700  ...                    0.2076          689.0
7   100812   100800  ...                       NaN            0.0
8   100830   831000  ...                    0.5966         1185.0
9   100858   100900  ...                    0.3134         9258.0
10  100937   101200  ...                    0.5052          677.0
11  101028  1218200  ...                    0.1406          569.0
12  101116  1303906  ...                    0.8667           90.0
13  101143   101500  ...                    0.1993          602.0
14  101161   106000  ...                     0.369         2558.0
15  101189   100300  ...                    0.7351          623.0
16  101240   101700  ...                         0         1867.0
17  101277  4187200  ...                    0.4634          123.0
18  101286   101800  ...                         0         1438.0
19  101295   787100  ...                    0.3119         1911.0

[20 rows x 1986 columns]

In [ ]:
# Look at the last 20 rows 
df.tail(20)

      UNITID     OPEID  ...  FTFTPCTFLOAN_POOLED_SUPP SCUGFFN_POOLED
6914  432029  01326301  ...                       NaN            NaN
6915  432038  03021501  ...                       NaN            NaN
6916  432047  02206201  ...                       NaN            NaN
6917  432065  03148400  ...                       NaN            NaN
6918  432074  02052703  ...                       NaN            NaN
6919  432117  01209201  ...                       NaN            NaN
6920  432126  031261B1  ...                       NaN            NaN
6921  432135  031261B2  ...                       NaN            NaN
6922  432278  03052202  ...                       NaN            NaN
6923  432296  03113102  ...                       NaN            NaN
6924  432302  03113103  ...                       NaN            NaN
6925  432311  03113104  ...                       NaN            NaN
6926  432384  030627A1  ...                       NaN            NaN
6927  432393  02218709  ...                       NaN            NaN
6928  432409  02218707  ...                       NaN            NaN
6929  432418  02148301  ...                       NaN            NaN
6930  432436  03032701  ...                       NaN            NaN
6931  432445  03205501  ...                       NaN            NaN
6932  432472  03065101  ...                       NaN            NaN
6933  432524  01195002  ...                       NaN            NaN

[20 rows x 1986 columns]

In [ ]:
# Look at a random sample of 20 rows    
df.sample(20)

        UNITID    OPEID  ...  FTFTPCTFLOAN_POOLED_SUPP SCUGFFN_POOLED
4034    368911  3066500  ...                         0          254.0
3248    221582   971000  ...                         0          331.0
5919    484923  4238700  ...                    0.4267           75.0
2790    209074   693800  ...                    0.5272         1929.0
6566  20627901  1092303  ...                       NaN            NaN
3438    229179   364600  ...                    0.5703         2527.0
2759    207722   316700  ...                    0.5704          412.0
5949    485546  4244000  ...         PrivacySuppressed           28.0
5744    481340  4213800  ...                    0.4318           44.0
2986    214892   490200  ...                    0.7931          145.0
6597  23368402   145906  ...                       NaN            NaN
1982    183202  2211600  ...                    0.7778           36.0
731     137476   146800  ...                    0.5483          425.0
469     123651   129300  ...                    0.9303          846.0
487     125091   133500  ...                         0         2187.0
939     146296   169900  ...                    0.1416         2041.0
4604    438674  2251600  ...                     0.975           40.0
5648    476896  4205200  ...                    0.8115          122.0
161     107725   573200  ...                         0          465.0
3571    233718   374200  ...                    0.8545          213.0

[20 rows x 1986 columns]

Read (with naked eyes, not computer) the dictionary and find out the definitions of the following 12 columns and copy the text next to the column name
- UNITID: Unit ID           
- INSTNM: Institution Name  
- CITY: City of College                   
- ZIP: Zip Code              
- ADM_RATE: Admit Rate       
- UGDS: Udergraduate Degree Studied              
- TUITIONFEE_IN:          
- MN_EARN_WNE_P10:

In [ ]:
# reimport the data with above 12 columns (ignore all other variables)
df.columns=("UNITID, INSTNM, CITY, STABBR, ZIP, ADM_RATE, UGDS, TUITIONFEE_INMN_EARN_WNE_P10")

TypeError: ignored

Sort from top to bottom by admit rate, take head(10)

In [ ]:
df.dtypes

UNITID                        int64
OPEID                         int64
OPEID6                        int64
INSTNM                       object
CITY                         object
                             ...
SCUGFFN                     float64
POOLYRS_FTFTAIDPCT          float64
FTFTPCTPELL_POOLED_SUPP      object
FTFTPCTFLOAN_POOLED_SUPP     object
SCUGFFN_POOLED              float64
Length: 1986, dtype: object

In [ ]:
# Find out the 10 colleges that are hardest to get in (top 10)
df.sort_values(by= "ADM_RATE")
df.head(10)

   UNITID    OPEID  ...  FTFTPCTFLOAN_POOLED_SUPP SCUGFFN_POOLED
0  100654   100200  ...                    0.7287         2698.0
1  100663   105200  ...                    0.5414         4176.0
2  100690  2503400  ...         PrivacySuppressed           24.0
3  100706   105500  ...                    0.4402         2544.0
4  100724   100500  ...                    0.7464         2094.0
5  100751   105100  ...                    0.4094        14863.0
6  100760   100700  ...                    0.2076          689.0
7  100812   100800  ...                       NaN            0.0
8  100830   831000  ...                    0.5966         1185.0
9  100858   100900  ...                    0.3134         9258.0

[10 rows x 1986 columns]

Sort from top to bottom by admit rate, take head(10)

In [ ]:
# 10. Find out the average in-state tuition of top 10
(Write code here)

Take average of head/earnings 10

In [ ]:
# Find out the average earnings of graduates from the top 10
(Write code here)

In [ ]:
sortby admit rate top 10 OR sort by admit rate H->L bottom 10 (tail)

In [ ]:
# Find out the 10 colleges that are easiest to get in (bottom 10)
(Write code here)

Take average of bottom 10 tail

In [ ]:
# Find out the average in-state tuition of the bottom 10
(Write code here)

Take average of bottom 10 tail

In [ ]:
# Find out the average earnings of graduates from the bottom 10
(Write code here)